IPADDR=`ip a|grep inet|grep ens33|awk -F '[ /]'+ '{print $3}'`
PREFIX=`ip a|grep inet|grep ens33|awk -F '[ /]'+ '{print $4}'`
GATEWAY=`ip route show |grep 'default via'|grep ens33|awk '{print $3}'`
DNS1='114.114.114.114'
ONBOOT='yes'
BOOTPROTO='static'
echo "IPADDR=$IPADDR">>/etc/sysconfig/network-scripts/ifcfg-ens33
echo "PREFIX=$PREFIX">>/etc/sysconfig/network-scripts/ifcfg-ens33
echo "GATEWAY=$GATEWAY">>/etc/sysconfig/network-scripts/ifcfg-ens33
echo "DNS1=$DNS1">>/etc/sysconfig/network-scripts/ifcfg-ens33
echo "ONBOOT=$ONBOOT">>/etc/sysconfig/network-scripts/ifcfg-ens33
echo "BOOTPROTO=$BOOTPROTO">>/etc/sysconfig/network-scripts/ifcfg-ens33
